quizExemples = [
    {
        quiz: [
            ["Quel est le nom de la planète imaginaire dans les confins de notre système solaire ?", ["Zéphyria", "Quasarion", "Célestia"]],
            ["Quel phénomène cosmique se produit lorsqu'une étoile explose et devient extrêmement brillante ?", ["Supernova", "Trou noir", "Nébuleuse"]],
            ["Quel est l'âge approximatif de l'univers ?", ["13,8 milliards d'années", "4 milliards d'années", "20 milliards d'années"]],
            ["Quelle lune de Jupiter est connue pour son océan souterrain ?", ["Europe", "Ganymède", "Callisto"]],
            ["Quel est le nom du premier satellite artificiel lancé dans l'espace ?", ["Spoutnik 1", "Vostok 1", "Explorer 1"]],
        ],
        from: "Marie",
        like: Math.floor(Math.random() * 100),
        name: "Défi Interstellaire",
        date: new Date(),
        category: "Espace",
    },
    {
        quiz: [
          ["Quel empereur romain a construit le Colisée à Rome ?", ["Jules César", "Néron", "Vespasien"]],
          ["Qui était le président des États-Unis pendant la guerre civile américaine ?", ["Abraham Lincoln", "Andrew Johnson", "Ulysses S. Grant"]],
          ["Quel événement a marqué le début de la Première Guerre mondiale en 1914 ?", ["L'assassinat de l'archiduc François-Ferdinand", "La bataille de la Somme", "Le traité de Versailles"]],
          ["Quelle civilisation ancienne a construit les pyramides de Gizeh en Égypte ?", ["Les Égyptiens", "Les Grecs", "Les Romains"]],
          ["Quel explorateur a réalisé le premier voyage autour du monde au XVIe siècle ?", ["Ferdinand Magellan", "Christophe Colomb", "Marco Polo"]],
        ],
        from: "Hugo",
        like: Math.floor(Math.random() * 100),
        name: "Défi Historique",
        date: new Date(),
        category: "Histoire",
    },
    {
        quiz: [
          ["Quel est le plus grand mammifère marin ?", ["Baleine bleue", "Orque", "Dauphin"]],
          ["Quel animal est capable de changer de couleur pour se camoufler ?", ["Caméléon", "Panthère", "Tigre"]],
          ["Quel oiseau est réputé pour imiter les sons de son environnement ?", ["Perroquet", "Corbeau", "Aigle"]],
          ["Quelle espèce de serpent est la plus venimeuse au monde ?", ["Cobra royal", "Vipère", "Mamba noir"]],
          ["Quel mammifère vole et est généralement actif la nuit ?", ["Chauve-souris", "Hibou", "Papillon"]],
        ],
        from: "Mattieu",
        like: Math.floor(Math.random() * 100),
        name: "Défi Animalier",
        date: new Date(),
        category: "Animaux",
    },
    {
        quiz: [
          ["Quel est le plus grand océan de la planète ?", ["Océan Atlantique", "Océan Indien", "Océan Pacifique"]],
          ["Quelle est la plus grande barrière de corail au monde ?", ["Barrière de corail des îles Fidji", "Grande Barrière de Corail", "Barrière de corail du Belize"]],
          ["Quel est le nom de l'animal marin le plus grand ?", ["Baleine bleue", "Requin blanc", "Orque"]],
          ["Quel pourcentage de la Terre est recouvert par les océans ?", ["70%", "50%", "97%"]],
          ["Quelle est la plus grande profondeur de l'océan ?", ["La fosse des Mariannes", "La fosse de Porto Rico", "La fosse de Java"]],
        ],
        from: "Marine Exploratrice",
        like: Math.floor(Math.random() * 100),
        name: "Aventure Océanique",
        date: new Date(),
        category: "Océan",
    },
    {
        quiz: [
          ["Quel est le jeu vidéo considéré comme le pionnier du genre battle royale ?", ["Fortnite", "PlayerUnknown's Battlegrounds (PUBG)", "Apex Legends"]],
          ["Quelle célèbre franchise de jeux vidéo met en scène le plombier Mario ?", ["Super Mario", "The Legend of Zelda", "Donkey Kong"]],
          ["Quel jeu est souvent considéré comme le premier jeu vidéo de l'histoire ?", ["Pong", "Space Invaders", "Pac-Man"]],
          ["Quelle entreprise japonaise est le créateur de la console de jeu PlayStation ?", ["Sony", "Microsoft", "Nintendo"]],
          ["Quel est le nom du célèbre jeu de construction et de survie avec des blocs ?", ["Minecraft", "Terraria", "Roblox"]],
        ],
        from: "John",
        like: Math.floor(Math.random() * 100),
        name: "Défi Jeux Vidéo",
        date: new Date(),
        category: "Jeux Vidéo",
    },
    {
        quiz: [
          ["Quel langage de programmation est souvent utilisé pour créer des pages web interactives ?", ["JavaScript", "Python", "Java"]],
          ["Quelle est la principale fonction du langage CSS dans le développement web ?", ["Gérer la présentation visuelle des pages", "Effectuer des calculs mathématiques", "Gérer les interactions côté serveur"]],
          ["Quel est le terme utilisé pour décrire une variable qui n'est accessible que dans la fonction où elle est déclarée ?", ["Locale", "Globale", "Statique"]],
          ["Qu'est-ce qu'un dépôt Git ?", ["Un endroit où sont stockées les copies d'un projet", "Un outil de compilation de code", "Un langage de programmation"]],
          ["Quelle méthode est utilisée pour imprimer du texte dans la console en JavaScript ?", ["console.log()", "print()", "log.console()"]],
        ],
        from: "Alice",
        like: Math.floor(Math.random() * 100),
        name: "Challenge Code",
        date: new Date(),
        category: "Code",
    },
    {
        quiz: [
          ["Quel est le plus grand pays d'Amérique du Sud en termes de superficie ?", ["Brésil", "Argentine", "Colombie"]],
          ["Quelle est la capitale de l'Australie ?", ["Sydney", "Melbourne", "Canberra"]],
          ["Quel fleuve traverse la ville de Paris ?", ["La Seine", "La Tamise", "Le Rhin"]],
          ["Quel est le plus haut sommet du monde ?", ["Mont Everest", "Mont Kilimandjaro", "Mont McKinley"]],
          ["Quel pays est situé à la pointe sud de l'Afrique ?", ["Afrique du Sud", "Nigeria", "Égypte"]],
        ],
        from: "Paul",
        like: Math.floor(Math.random() * 100),
        name: "Défi Géographique",
        date: new Date(),
        category: "Géographie",
    },
    {
        quiz: [
          ["Quel matériau est nécessaire pour fabriquer une pioche en diamant dans Minecraft ?", ["Fer", "Diamant", "Bois"]],
          ["Quelle créature hostile apparaît principalement la nuit dans Minecraft ?", ["Zombie", "Loup", "Golem de fer"]],
          ["Comment s'appelle le monde de l'Enfer dans Minecraft ?", ["Le Nether", "L'End", "Le Sous-Monde"]],
          ["Quel bloc est nécessaire pour créer un portail vers le Nether ?", ["Obsidienne", "Pierre", "Verre"]],
          ["Quel est le nom du dragon que les joueurs combattent dans le monde de l'End ?", ["Enderdragon", "Wither", "Herobrine"]],
        ],
        from: "Steve",
        like: Math.floor(Math.random() * 100),
        name: "Défi Minecraftien",
        date: new Date(),
        category: "Minecraft",
    },
    {
        quiz: [
          ["Quel est l'ingrédient principal de la sauce pesto ?", ["Basilic", "Persil", "Menthe"]],
          ["Quel plat italien est composé de fines tranches de viande ou de légumes, souvent marinées ?", ["Carpaccio", "Bruschetta", "Frittata"]],
          ["Quelle est la principale épice utilisée dans le curry indien ?", ["Curcuma", "Cumin", "Coriandre"]],
          ["Quel type de pâtes ressemble à de petits grains de riz et est souvent utilisé dans la cuisine asiatique ?", ["Orzo", "Udon", "Couscous"]],
          ["Quel dessert français est composé de couches de pâte feuilletée et de crème pâtissière ?", ["Mille-feuille", "Éclair", "Tarte Tatin"]],
        ],
        from: "Julia",
        like: Math.floor(Math.random() * 100),
        name: "Délice Culinaire",
        date: new Date(),
        category: "Cuisine",
    },
    {
        quiz: [
          ["Quel instrument de musique est souvent associé au jazz ?", ["Saxophone", "Violon", "Flûte"]],
          ["Quel genre musical a été popularisé par des artistes tels que Elvis Presley et Chuck Berry dans les années 1950 ?", ["Rock 'n' Roll", "Blues", "Country"]],
          ["Quel est le nom du célèbre festival de musique qui se déroule chaque été dans l'État du Tennessee, aux États-Unis ?", ["Coachella", "Glastonbury", "Bonnaroo"]],
          ["Quelle chanson de Michael Jackson a été un grand succès en 1982 et a remporté huit Grammy Awards en une seule nuit ?", ["Thriller", "Billie Jean", "Beat It"]],
          ["Quel est le genre musical associé aux îles de la Jamaïque et à des artistes tels que Bob Marley ?", ["Reggae", "Salsa", "Hip-hop"]],
        ],
        from: "David",
        like: Math.floor(Math.random() * 100),
        name: "Harmonie Musicale",
        date: new Date(),
        category: "Musique",
    },
    {
        quiz: [
          ["Quel réalisateur a dirigé le film 'Inception' en 2010 ?", ["Christopher Nolan", "Quentin Tarantino", "Steven Spielberg"]],
          ["Quel acteur a remporté un Oscar pour son rôle dans 'The Revenant' en 2016 ?", ["Leonardo DiCaprio", "Brad Pitt", "Matthew McConaughey"]],
          ["Quel film d'animation met en scène un rat qui rêve de devenir un grand chef cuisinier à Paris ?", ["Ratatouille", "Finding Nemo", "Shrek"]],
          ["Quelle actrice incarne Katniss Everdeen dans la série de films 'The Hunger Games' ?", ["Jennifer Lawrence", "Emma Watson", "Scarlett Johansson"]],
          ["Quel est le premier film de la trilogie 'The Lord of the Rings' ?", ["The Fellowship of the Ring", "The Two Towers", "The Return of the King"]],
        ],
        from: "Sophie",
        like: Math.floor(Math.random() * 100),
        name: "Cinéphile Challenge",
        date: new Date(),
        category: "Cinéma",
    },
    {
        quiz: [
          ["Quel est l'élément le plus abondant dans l'univers ?", ["Hydrogène", "Hélium", "Oxygène"]],
          ["Quelle est la plus petite particule constituante de la matière ?", ["Quark", "Électron", "Proton"]],
          ["Quelle est la planète la plus proche du Soleil ?", ["Mercure", "Vénus", "Mars"]],
          ["Quel scientifique a formulé la théorie de la relativité restreinte ?", ["Albert Einstein", "Isaac Newton", "Galilée"]],
          ["Quelle est la fonction principale des mitochondries dans une cellule ?", ["Production d'énergie", "Stockage des nutriments", "Synthèse des protéines"]],
        ],
        from: "Thomas",
        like: Math.floor(Math.random() * 100),
        name: "Défi Scientifique",
        date: new Date(),
        category: "Science",
    },
    {
        quiz: [
          ["Quelle est la somme des angles d'un triangle ?", ["180 degrés", "90 degrés", "360 degrés"]],
          ["Quel est le résultat de 15 * 7 - 20 ?", ["85", "105", "115"]],
          ["Quelle est la racine carrée de 144 ?", ["12", "14", "16"]],
          ["Si x = 5 et y = 3, quelle est la valeur de x² + y² ?", ["34", "40", "50"]],
          ["Quelle est la valeur de π (pi) arrondie à dix décimales ?", ["3.1415926535", "3.1415824785", "3.1415976530"]],
        ],
        from: "Sophie",
        like: Math.floor(Math.random() * 100),
        name: "Défi Mathématique",
        date: new Date(),
        category: "Mathématiques",
    },
    {
        quiz: [
          ["Qu'est-ce que l'apprentissage automatique (machine learning) ?", ["Un sous-domaine de l'IA permettant aux machines d'apprendre sans être explicitement programmées", "Un programme qui simule le raisonnement humain", "Un ensemble de règles conditionnelles"]],
          ["Quelle entreprise a développé le système d'IA nommé Watson, qui a remporté Jeopardy! en 2011 ?", ["IBM", "Google", "Microsoft"]],
          ["Quel type d'IA est conçu pour accomplir des tâches spécifiques sans être programmé explicitement pour chacune ?", ["IA spécialisée (ou étroite)", "IA générale", "IA forte"]],
          ["Quel algorithme d'apprentissage automatique est souvent utilisé pour la classification ?", ["SVM (Support Vector Machine)", "K-means", "Random Forest"]],
          ["Qu'est-ce que le terme 'IA faible' (ou 'IA étroite') désigne-t-il ?", ["IA conçue pour une tâche spécifique, ne possédant pas de compréhension ou de conscience", "IA avec une intelligence équivalente à celle humaine", "IA capable de surpasser l'intelligence humaine"]],
        ],
        from: "Alexandre",
        like: Math.floor(Math.random() * 100),
        name: "Défi IA",
        date: new Date(),
        category: "IA",
    },
    {
        quiz: [
          ["Qu'est-ce que l'effet de bokeh en photographie ?", ["Un flou artistique d'arrière-plan", "Un filtre de couleur", "Une mise au point nette"]],
          ["Quel type d'appareil photo est réputé pour sa compacité et sa simplicité d'utilisation ?", ["Appareil photo compact", "Reflex", "Appareil photo hybride"]],
          ["Qu'est-ce que la règle des tiers en composition photographique ?", ["Une technique de placement des sujets sur des points d'intérêt", "Une mesure d'exposition", "Une méthode de post-production"]],
          ["Quel est le principal avantage d'un objectif à focale fixe par rapport à un objectif à focale variable ?", ["Ouverture plus large pour une meilleure performance en basse lumière", "Zoom optique puissant", "Stabilisation d'image intégrée"]],
          ["Quel est le nom du processus chimique utilisé pour développer des films photographiques en noir et blanc ?", ["Révélation", "Exposition", "Fixation"]],
        ],
        from: "Sophie",
        like: Math.floor(Math.random() * 100),
        name: "Défi Photographique",
        date: new Date(),
        category: "Photographie",
      }
];

module.exports = { quizExemples };
